### ISSUE TITLE
Doesn't start.

### ISSUE THREAD

**Issue by StealthOrc** [ekgame/osu-auto-host#1]
Hey there,
I just saw your reddit post and also looked up all of your other work and searched for a solution since yesterday evening ... and I also configured the settings file and it always shows up for about a second with this: https://gyazo.com/cc7c0b01fed434baa3be9fad7e25a70f

I might be overlooking something, but still cant figure out the mistake (since im just a stundent who just started programming xD)

**Comment by ekgame** [comment]
I wouldn't recommend actually running the bot in it's current state. There are numerous glaring problems that I plan to look into in the coming weeks/months. I've been working on merging the bancho-api and bancho-client projects into one and writing proper handling for most things. After that is relatively complete, I'll be rewriting the auto-host for the new API.
